Repository GEOS-ESM/ESMA_cmake, pull requests merged in 2020-11, with the labels that each got.

#133 Enable independent use with external dependencies.
  FindBaselibs.cmake
  esma.cmake
Labels: 0 diff

#134 Merge Develop into main
  .circleci/config.yml
  CHANGELOG.md
  FindBaselibs.cmake
  esma.cmake
Labels: 0 diff

#135 Remove support for manage_externals
  Externals.cfg
Labels: 0 diff trivial

#136 Merge Develop into main: remove manage_externals support
  CHANGELOG.md
  Externals.cfg
Labels: 0 diff structural, 0 diff trivial

#138 Move to CircleCI Medium Resource Class
  .circleci/config.yml
Labels: 0 diff

#139 Merge Develop into Main [skip ci]
  .circleci/config.yml
Labels: 0 diff trivial
