Repository GEOS-ESM/ESMA_cmake, pull requests merged in 2021-09, with the labels that each got.

#203 Add librt and libdl to the ESMF libraries
  CHANGELOG.md
  FindBaselibs.cmake
Labels: bugfix, 0 diff structural, 0 diff

#209 Update licenses on develop
  COPYRIGHT
  LICENSE
  LICENSE-NOSA
  README.md
Labels: documentation, 0 diff trivial

#212 Fixes needed for handling mepo style options.
  CHANGELOG.md
  esma.cmake
  esma_add_library.cmake
  esma_add_subdirectories.cmake
  esma_mepo_style.cmake
Labels: enhancement, 0 diff structural

#211 Add code to prevent directories with commas
  CHANGELOG.md
  esma.cmake
Labels: enhancement, 0 diff

#213 Merge develop into main for 3.5.6 Release
  CHANGELOG.md
  esma.cmake
  esma_add_library.cmake
  esma_add_subdirectories.cmake
  esma_mepo_style.cmake
Labels: 0 diff

#214 Fix for pthread and NAG on Linux
  CHANGELOG.md
  esma.cmake
Labels: bugfix, 0 diff

#215 Pull NAG Fix from Develop to Main for Release
  CHANGELOG.md
  esma.cmake
Labels: bugfix, 0 diff

#207 Refactor ESMA_cmake
  .gitrepo
  CHANGELOG.md
  README.md
  compiler/checks/CheckFortranSupport.cmake
  compiler/checks/assumed_type.F90
  compiler/checks/check_fortran_support.cmake
  compiler/checks/findloc.F90
  compiler/checks/impure_elemental.F90
  compiler/checks/test.F90
  compiler/checks/try_fortran_compile.cmake
  compiler/esma_compiler.cmake
  compiler/flags/GNU_Fortran.cmake
  compiler/flags/Generic_Fortran.cmake
  compiler/flags/Intel_Fortran.cmake
  compiler/flags/NAG_Fortran.cmake
  compiler/flags/PGI_Fortran.cmake
  esma.cmake
  esma_support/esma_add_library.cmake
  esma_support/esma_add_subdirectories.cmake
  esma_support/esma_check_if_debug.cmake
  esma_support/esma_config_subcomponents.cmake
  esma_support/esma_create_stub_component.cmake
  esma_support/esma_enable_tests.cmake
  esma_support/esma_fortran_generator_list.cmake
  esma_support/esma_generate_automatic_code.cmake
  esma_support/esma_mepo_style.cmake
  esma_support/esma_set_this.cmake
  esma_support/esma_support.cmake
  external_libraries/DetermineSite.cmake
  external_libraries/FindBaselibs.cmake
  external_libraries/FindGitInfo.cmake
  external_libraries/math_libraries.cmake
  latex/FindProtex.cmake
  latex/UseLatex.cmake
  latex/UseProTeX.cmake
  latex/esma_latex.cmake
  operating_system/osx_extras.cmake
  python/esma_check_python2_module.cmake
  python/esma_check_python3_module.cmake
  python/esma_check_python_module.cmake
  python/esma_find_python2_module.cmake
  python/esma_find_python3_module.cmake
  python/esma_find_python_module.cmake
  python/esma_python.cmake
  python/f2py/FindF2PY.cmake
  python/f2py/UseF2Py.cmake
  python/f2py/esma_add_f2py_module.cmake
  python/f2py/test.F90
  python/f2py/try_f2py_compile.cmake
  python/f2py2/FindF2PY2.cmake
  python/f2py2/UseF2Py2.cmake
  python/f2py2/esma_add_f2py2_module.cmake
  python/f2py2/test.F90
  python/f2py2/try_f2py2_compile.cmake
  python/f2py3/FindF2PY3.cmake
  python/f2py3/UseF2Py3.cmake
  python/f2py3/esma_add_f2py3_module.cmake
  python/f2py3/test.F90
  python/f2py3/try_f2py3_compile.cmake
Labels: 0 diff, Contingent - DNA
