Repository GEOS-ESM/ESMA_cmake, pull requests merged in 2021-04, with the labels that each got.

#162 Update CI image to 6.1.0
  .circleci/config.yml
Labels: 0 diff structural, 0 diff trivial

#163 Enable GFE namespace use.
  CHANGELOG.md
  esma.cmake
Labels: 0 diff trivial

#164 Merge Develop into Main for release
  .circleci/config.yml
  CHANGELOG.md
  esma.cmake
Labels: 0 diff

#165 add option to BUILD_WITH_PFLOGGER
  CHANGELOG.md
  FindBaselibs.cmake
Labels: 0 diff

#166 Merge Develop into Main
  CHANGELOG.md
  FindBaselibs.cmake
Labels: 0 diff structural, gitflow

#168 Add CONTRIBUTING and CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: 0 diff trivial

#169 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 0 diff trivial

#170 Fix misspelling in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 0 diff trivial

#159 Updates to use Python2 and Python3 at same time
  CHANGELOG.md
  FindF2PY2.cmake
  FindF2PY3.cmake
  UseF2Py2.cmake
  UseF2Py3.cmake
  check_compiler_support/try_f2py2_compile.cmake
  check_compiler_support/try_f2py3_compile.cmake
  esma.cmake
  esma_add_f2py2_module.cmake
  esma_add_f2py3_module.cmake
  esma_add_f2py_module.cmake
  esma_check_python2_module.cmake
  esma_check_python3_module.cmake
  esma_find_python2_module.cmake
  esma_find_python3_module.cmake
Labels: 0 diff structural

#171 Merge develop (python2/3) into main
  CHANGELOG.md
  FindF2PY2.cmake
  FindF2PY3.cmake
  UseF2Py2.cmake
  UseF2Py3.cmake
  check_compiler_support/try_f2py2_compile.cmake
  check_compiler_support/try_f2py3_compile.cmake
  esma.cmake
  esma_add_f2py2_module.cmake
  esma_add_f2py3_module.cmake
  esma_add_f2py_module.cmake
  esma_check_python2_module.cmake
  esma_check_python3_module.cmake
  esma_find_python2_module.cmake
  esma_find_python3_module.cmake
Labels: 0 diff
