Repository GEOS-ESM/ESMA_cmake, pull requests merged in 2021-06, with the labels that each got.

#185 Improved fix for #175 - custom FPP defs.
  CHANGELOG.md
  esma.cmake
  esma_add_library.cmake
  esma_set_this.cmake
Labels: 0 diff trivial, enhancement

#187 Add ability to detect BASEDIR from environment
  CHANGELOG.md
  FindBaselibs.cmake
Labels: 0 diff

#188 Merge Develop into Main for release
  CHANGELOG.md
  FindBaselibs.cmake
  esma.cmake
  esma_add_library.cmake
  esma_set_this.cmake
Labels: 0 diff

#184 Enable GFE Namespace
  .circleci/config.yml
  CHANGELOG.md
  FindBaselibs.cmake
  UseF2Py.cmake
  UseF2Py2.cmake
  UseF2Py3.cmake
  esma.cmake
Labels: 0 diff

#189 Use ESMF dylib on macOS
  CHANGELOG.md
  FindBaselibs.cmake
Labels: 0 diff

#190 Merge Develop into Main for 3.5.0 Release
  .circleci/config.yml
  CHANGELOG.md
  FindBaselibs.cmake
  UseF2Py.cmake
  UseF2Py2.cmake
  UseF2Py3.cmake
  esma.cmake
Labels: 0 diff, gitflow
