Repository GEOS-ESM/ESMA_cmake, pull requests merged in 2022-06, with the labels that each got.

#272 Fixes #271
  CHANGELOG.md
  compiler/flags/GNU_Fortran.cmake
  compiler/flags/NAG_Fortran.cmake
  python/esma_python.cmake
Labels: enhancement, 0 diff

#273 Merge Develop into main for release
  CHANGELOG.md
  compiler/flags/GNU_Fortran.cmake
  compiler/flags/NAG_Fortran.cmake
  python/esma_python.cmake
Labels: 0 diff

#274 Changes needed to run GEOS on M1
  CHANGELOG.md
  compiler/flags/GNU_Fortran.cmake
  compiler/flags/Intel_Fortran.cmake
Labels: 0 diff

#276 Fixes for GCC 12. Update to haswell by default
  CHANGELOG.md
  compiler/flags/GNU_Fortran.cmake
Labels: 0 diff, Non 0-diff

#277 Merge Develop into Main for release
  CHANGELOG.md
  compiler/flags/GNU_Fortran.cmake
  compiler/flags/Intel_Fortran.cmake
Labels: 0 diff, Non 0-diff
