Repository GEOS-ESM/ESMA_cmake, pull requests merged in 2024-08, with the labels that each got.

#394 v3: Add the SMOD word in the target submodule file name
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
Labels: 0 diff

#393 Add the SMOD word in the target submodule file name.
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
Labels: 0 diff trivial

#395 GitFlow: Merge develop into main for release
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
Labels: 0 diff, gitflow

#398 Workaround for OpenMP + NAG + CMake (v3)
  CHANGELOG.md
  compiler/flags/NAG_Fortran.cmake
  esma.cmake
Labels: 0 diff

#397 Workaround for OpenMP + NAG + CMake
  CHANGELOG.md
  compiler/flags/NAG_Fortran.cmake
  esma.cmake
Labels: 0 diff

#399 GitFlow: develop into main
  CHANGELOG.md
  compiler/flags/NAG_Fortran.cmake
  esma.cmake
Labels: 0 diff

#400 v3.6: Updates needed to run on SLES15 at NCCS
  .editorconfig
  CHANGELOG.md
  external_libraries/DetermineSite.cmake
  python/f2py2/FindF2PY2.cmake
Labels: 0 diff
