Repository GEOS-ESM/ESMA_cmake, pull requests merged in 2024-06, with the labels that each got.

#381 Fixes for Python 3.12, meson, and f2py (v3 branch)
  CHANGELOG.md
  python/f2py3/UseF2Py3.cmake
Labels: 0 diff

#382 Fixes for Python 3.12, meson, and f2py
  CHANGELOG.md
  python/f2py3/UseF2Py3.cmake
Labels: 0 diff

#380 Fixes for NVHPC
  CHANGELOG.md
  external_libraries/FindBaselibs.cmake
  python/f2py/FindF2PY.cmake
  python/f2py2/FindF2PY2.cmake
  python/f2py3/FindF2PY3.cmake
Labels: 0 diff

#383 GitFlow: Merge Develop into main for release
  CHANGELOG.md
  external_libraries/FindBaselibs.cmake
  python/f2py/FindF2PY.cmake
  python/f2py2/FindF2PY2.cmake
  python/f2py3/FindF2PY3.cmake
Labels: 0 diff, gitflow

#385 Add esma_add_fortran_submodules (v3)
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
  esma_support/esma_support.cmake
Labels: 0 diff

#384 New function
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
  esma_support/esma_support.cmake
Labels: 0 diff trivial, 0 diff

#386 GitFlow: Merge develop into main for release
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
  esma_support/esma_support.cmake
Labels: 0 diff, gitflow
