Repository GEOS-ESM/ESMA_cmake, pull requests merged in 2024-07, with the labels that each got.

#388 v3: Update the file esma_add_fortran_submodules.cmake
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
Labels: 0 diff

#387 Update the file esma_add_fortran_submodules.cmake
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
Labels: 0 diff trivial

#389 GitFlow: Merge develop into main for release
  CHANGELOG.md
  esma_support/esma_add_fortran_submodules.cmake
Labels: 0 diff

#390 v3: Move detection of MPI out of FindBaselibs
  CHANGELOG.md
  esma.cmake
  external_libraries/FindBaselibs.cmake
Labels: 0 diff

#391 Move detection of MPI out of FindBaselibs
  CHANGELOG.md
  esma.cmake
  external_libraries/FindBaselibs.cmake
Labels: 0 diff

#392 GitFlow: develop to main
  CHANGELOG.md
  esma.cmake
  external_libraries/FindBaselibs.cmake
Labels: 0 diff, gitflow
